### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by EnkrateiaLucca** [kpolley/GitChat#4]
Hi! I tried installing with npm install but I get a dependency error with langchain community. See below:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @langchain/community@0.0.13
npm ERR! Found: @vercel/kv@1.0.1
npm ERR! node_modules/@vercel/kv
npm ERR!   @vercel/kv@"^1.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @vercel/kv@"^0.2.3" from @langchain/community@0.0.13
npm ERR! node_modules/@langchain/community
npm ERR!   @langchain/community@"^0.0.13" from the root project
npm ERR!   @langchain/community@"~0.0.12" from langchain@0.0.213
npm ERR!   node_modules/langchain
npm ERR!     langchain@"^0.0.213" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @vercel/kv@0.2.4
npm ERR! node_modules/@vercel/kv
npm ERR!   peerOptional @vercel/kv@"^0.2.3" from @langchain/community@0.0.13
npm ERR!   node_modules/@langchain/community
npm ERR!     @langchain/community@"^0.0.13" from the root project
npm ERR!     @langchain/community@"~0.0.12" from langchain@0.0.213
npm ERR!     node_modules/langchain
npm ERR!       langchain@"^0.0.213" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/greatmaster/.npm/_logs/2024-01-18T13_04_10_688Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/greatmaster/.npm/_logs/2024-01-18T13_04_10_688Z-debug-0.log

Any tips? Cheers! :)

**Comment by kpolley** [comment]
👋 I use [nix](https://github.com/kpolley/GitChat/blob/main/shell.nix) for package management so it may have cause some packages to not be installed. can you try again using this branch? https://github.com/kpolley/GitChat/pull/5
